### ISSUE TITLE
SocketAsyncEventArgs exception thrown on high packet volume

### ISSUE THREAD

**Issue by alin1337** [Eastrall/LiteNetwork#51] opened 2022-05-08 13:08 UTC
I noticed sending a lot of data from server to client some of the data would not arrive in the client.
After overriding OnError method, i got the following exception 
`An asynchronous socket operation is already in progress using this SocketAsyncEventArgs instance. `

at

https://github.com/Eastrall/LiteNetwork/blob/0b2ce5fcf6a31a988df85c6c2e29e026a8bc9f00/src/LiteNetwork/Internal/LiteSender.cs#L118 

This exception is raised when sending a lot of packets at once (in a loop), the _socketAsyncEvent is still locked when SendAsync returns false and tries to free the buffer.
The packets are sent after OnConnected is called.

A quick and dirty fix is to create another SocketAsyncEventArgs every time a packet is sent (as this seem to be a working solution for me)

**Comment by alin1337** [comment] 2022-05-08 16:32
An example on how to replicate this crash.
https://gist.github.com/alin1337/fa27ddd434ca39f2359cf0686e8cbf2f

**Comment by Eastrall** [comment] 2022-05-09 19:24
Hi, thank you for the feedback! I will look into this. 😄

**Comment by Eastrall** [comment] 2022-05-14 09:37
@alin1337 Tried again your sample with version `2.0.0-rc.5` and I was not able to reproduce the issue. I also have increased to amount of packets to 20, 50 and 100, and everything goes fine.

Closing the issue.
Feel free to re-open if needed.

**Closed by Eastrall** 2022-05-14 09:37 UTC
Labels: bug, comp: sender
